// units.ts
import type { UnitTiers } from './types';

export const DEFAULT_UNIT_TIERS: UnitTiers = {
    "Legendary": ["Falconetti Gunners", "Pavise Crossbowmen", "Silahdars", "Siphonarioi", "Liao's Rangers", "Shieldmaidens", "Modao Battalion", "Shenji Grenadiers", "Houndsmen", "Chevaliers", "Varangian Guards", "Retiarii", "Hashashins", "Queen's Knights", "Yanyuedao Cavalry", "Orochi Samurai", "Zweihanders", "Xuanjia Heavy Cavalry", "Sunward Phalanx", "Lionroar Crew", "Hwarang", "Empire Chariot", "Cataphract Lancers", "Fire Lancers", "Iron Reapers", "Monastic Knights", "Tercio Arquebusiers", "Winged Hussars", "Kheshigs", "Rattan Rangers", "Spartan Chosen", "Order of the Dragon"],
    "Epic": ["Fortebraccio Pikemen", "Azaps", "Sipahis", "Symmachean Paladins", "Symmachean Stalwarts", "Armiger Lancers", "Berserkers", "Greyhair Garrison", "Axe Raiders", "Claymores", "Banner Guards", "Huskarls", "Myrmillones", "Camel Lancers", "Crescent Monks", "Matchlock Ashigaru", "Onna-Musha", "Kriegsbruders", "Perceval's Royal Guard", "Wuwei Mansion Guard", "Companion Cavalry", "Swinefeathers", "Tiger Fists", "Halberd Elite", "Dagger-Axe Lancers", "Halberdier Sergeants", "Imperial Archers", "Imperial Arquebusiers", "Imperial Javelineers", "Imperial Pike Guards", "Imperial Spear Guards", "Javelin Sergeants", "Kriegsrat Fusiliers", "Men-at-Arms", "Palace Guards", "Prefecture Heavy Cavalry", "Spear Sergeants", "Vassal Longbowmen", "Yeomen", "Khevtuul Cavalry", "Tseregs", "Galahad Spearmen", "Laconic Javelins", "Zealot"],
    "Rare": ["Demesne Arbalists", "Demesne Arquebusiers", "Halberdiers", "Incendiary Archers", "Ironcap Spearmen", "Mace Sergeants", "Prefecture Archers", "Prefecture Guards", "Prefecture Pikemen", "Rattan Marksmen", "Rattan Vipers", "Vanguard Archers", "Black Dragon Javelineers", "Black Dragon Pikemen", "Black Dragon Spearmen", "Alchemists", "Cudgel Monks", "Janissaries", "Outriders", "Namkhan Archers", "Sons of Fenrir", "Condottieri Guards", "Dimachaeri", "Jangjus", "Khorchins", "Reitar Pistoleers", "Selemchid Cavalry", "Zykalian Militia", "Feathered Crossbowmen", "Psiloi Slingers", "Ronin", "Qin's Footbow", "Bagpipers", "Bedivere Rangers", "Silla Guards", "Schutzdieners", "Helot Auxilary", "Landsknechts", "Naginata Monks", "Squires", "Wuxing Pikemen", "Doppelsoldner"],
    "Uncommon": ["Black Dragon Archers", "Sea Stag Deathdealers", "Coutiliers", "Demesne Archers", "Demesne Crossbowmen", "Demesne Javelineers", "Demesne Spearmen", "Ironcap Archers", "Ironcap Arquebusiers", "Ironcap Bowriders", "Ironcap Scout Cavalry", "Ironcap Swordsmen", "Javelin Militia", "Pike Militia", "Rattan Pikemen", "Rattan Roundshields"],
    "Common": ["Serfs", "Tenant Farmers", "Village Watchmen", "Woodcutters", "Martellatori", "Spear Militia", "Sword Militia", "Demesne Pikemen", "Levy Bowmen"]
};